# Generated by Django 5.1.5 on 2025-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YtmMapping',
            fields=[
                ('isin', models.TextField(db_column='ISIN', primary_key=True, serialize=False)),
                ('mapping', models.TextField(db_column='Mapping')),
            ],
            options={
                'db_table': 'YtmMapping',
            },
        ),
    ]
