# Generated by Django 5.1.5 on 2025-02-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0005_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='cluster',
            field=models.TextField(db_column='Cluster'),
        ),
    ]
