# Generated by Django 5.1.5 on 2025-02-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0007_currencyfactormultiplier_drivers_ter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='market_ts',
            field=models.TextField(db_column='Market Ts'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='subscription_bbg',
            field=models.TextField(db_column='Subscription BBG'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='subscription_ts',
            field=models.TextField(db_column='Subscription Ts'),
        ),
    ]
