# Generated by Django 5.1.5 on 2025-02-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0011_alter_ytmmapping_mapping_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytmmapping',
            name='instrument_type',
        ),
    ]
