# Generated by Django 5.1.5 on 2025-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0015_ytmmapping_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyfactormultiplier',
            name='currency_exchange',
            field=models.TextField(db_column='Currency Exchange', primary_key=True, serialize=False),
        ),
    ]
