# Generated by Django 5.1.5 on 2025-02-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0017_delete_currencyfactormultiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyFactorMultiplier',
            fields=[
                ('currency_exchange', models.TextField(db_column='Currency Exchange', primary_key=True, serialize=False)),
                ('multiplier', models.FloatField(blank=True, db_column='Multiplier', null=True)),
            ],
            options={
                'db_table': 'CurrencyFactorMultiplier',
            },
        ),
    ]
