# Generated by Django 5.1.5 on 2025-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0019_brothers_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brothers',
            name='weight',
            field=models.FloatField(blank=True, db_column='Weight', null=True),
        ),
    ]
