# Generated by Django 5.1.5 on 2025-02-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0022_alter_currencyexposuremanual_hedged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyexposuremanual',
            name='value',
        ),
        migrations.AddField(
            model_name='currencyexposuremanual',
            name='weight',
            field=models.FloatField(blank=True, db_column='Weight', null=True),
        ),
        migrations.AlterField(
            model_name='currencyexposuremanual',
            name='currency',
            field=models.TextField(blank=True, db_column='Currency', null=True),
        ),
        migrations.AlterField(
            model_name='currencyexposuremanual',
            name='hedged',
            field=models.TextField(blank=True, db_column='Hedged', null=True),
        ),
        migrations.AlterField(
            model_name='currencyexposuremanual',
            name='ticker',
            field=models.TextField(blank=True, db_column='Ticker', null=True),
        ),
    ]
