# Generated by Django 5.1.5 on 2025-02-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0023_remove_currencyexposuremanual_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyExposureManual',
        ),
    ]
