# Generated by Django 5.1.5 on 2025-02-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0012_remove_ytmmapping_instrument_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YtmMapping',
        ),
    ]
