# Generated by Django 5.1.5 on 2025-01-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brothers',
            fields=[
                ('isin', models.TextField(db_column='ISIN', primary_key=True, serialize=False)),
                ('cluster', models.TextField(blank=True, db_column='Cluster', null=True)),
            ],
            options={
                'db_table': 'Brothers',
            },
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.TextField(db_column='ISIN')),
                ('exchange', models.TextField(db_column='Exchange')),
                ('trading_currency', models.TextField(db_column='Trading Currency')),
                ('fund_currency', models.TextField(blank=True, db_column='Fund Currency', null=True)),
                ('ticker', models.TextField(blank=True, db_column='Ticker', null=True)),
            ],
            options={
                'db_table': 'Instruments',
                'unique_together': {('isin', 'exchange', 'ticker')},
            },
        ),
    ]
