# Generated by Django 5.1.5 on 2025-01-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0002_ytmmapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instruments',
            unique_together={('isin', 'exchange', 'trading_currency')},
        ),
    ]
