# Generated by Django 5.1.5 on 2025-02-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0003_alter_instruments_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='brothers',
            name='weight',
            field=models.FloatField(db_column='Weight', default=0.0),
        ),
        migrations.AlterField(
            model_name='brothers',
            name='cluster',
            field=models.IntegerField(blank=True, db_column='Cluster', null=True),
        ),
    ]
