# Generated by Django 5.1.5 on 2025-02-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0004_brothers_weight_alter_brothers_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('isin', models.TextField(db_column='ISIN', primary_key=True, serialize=False)),
                ('ticker', models.TextField(db_column='Ticker')),
                ('cluster', models.IntegerField(db_column='Cluster')),
                ('subcluster', models.IntegerField(db_column='Subcluster')),
            ],
            options={
                'db_table': 'Clusters',
            },
        ),
    ]
