# Generated by Django 5.1.5 on 2025-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0006_alter_clusters_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyFactorMultiplier',
            fields=[
                ('currency_exchange', models.FloatField(db_column='Currency Exchange', primary_key=True, serialize=False)),
                ('multiplier', models.FloatField(blank=True, db_column='Multiplier', null=True)),
            ],
            options={
                'db_table': 'CurrencyFactorMultiplier',
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('name', models.TextField(db_column='Name', primary_key=True, serialize=False)),
                ('subscription_ts', models.IntegerField(db_column='Subscription Ts')),
                ('market_ts', models.IntegerField(db_column='Market Ts')),
                ('subscription_bbg', models.FloatField(db_column='Subscription BBG')),
            ],
            options={
                'db_table': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='Ter',
            fields=[
                ('isin', models.TextField(db_column='ISIN', primary_key=True, serialize=False)),
                ('hard_coding', models.FloatField(blank=True, db_column='Hard Coding', null=True)),
            ],
            options={
                'db_table': 'Ter',
            },
        ),
        migrations.RemoveField(
            model_name='ytmmapping',
            name='mapping',
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='hard_coding',
            field=models.FloatField(blank=True, db_column='Hard Coding', null=True),
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='instrument',
            field=models.TextField(blank=True, db_column='Instrument', null=True),
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='mapping_subscription',
            field=models.IntegerField(blank=True, db_column='Mapping Subscription', null=True),
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='repo_rate',
            field=models.FloatField(blank=True, db_column='Repo Rate', null=True),
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='subscription',
            field=models.IntegerField(blank=True, db_column='Subscription', null=True),
        ),
        migrations.CreateModel(
            name='HedgeRatioCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_isin', models.TextField(db_column='Target ISIN')),
                ('target_ticker', models.TextField(db_column='Target Ticker')),
                ('driver_isin', models.TextField(db_column='Driver ISIN')),
                ('driver_ticker', models.TextField(db_column='Driver Ticker')),
                ('beta', models.FloatField(db_column='Beta')),
            ],
            options={
                'db_table': 'HedgeRatioCluster',
                'unique_together': {('target_isin', 'driver_isin')},
            },
        ),
        migrations.CreateModel(
            name='HedgeRatioDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_isin', models.TextField(db_column='Target_ISIN')),
                ('target_ticker', models.TextField(db_column='Target_Ticker')),
                ('driver', models.TextField(db_column='Driver')),
                ('beta', models.FloatField(db_column='Beta')),
            ],
            options={
                'db_table': 'HedgeRatioDriver',
                'unique_together': {('target_isin', 'driver')},
            },
        ),
    ]
