# Generated by Django 5.1.5 on 2025-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0008_alter_drivers_market_ts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='market_ts',
            field=models.TextField(blank=True, db_column='Market Ts', null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='subscription_ts',
            field=models.TextField(blank=True, db_column='Subscription Ts', null=True),
        ),
    ]
