# Generated by Django 5.1.5 on 2025-02-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0009_alter_drivers_market_ts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytmmapping',
            name='instrument',
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='instrument_type',
            field=models.TextField(blank=True, db_column='Instrument Type', null=True),
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='mapping_isin',
            field=models.TextField(blank=True, db_column='Mapping ISIN', null=True),
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='mapping_name',
            field=models.IntegerField(blank=True, db_column='Mapping Name', null=True),
        ),
        migrations.AddField(
            model_name='ytmmapping',
            name='name',
            field=models.TextField(db_column='Name', default=None),
        ),
        migrations.AlterField(
            model_name='ytmmapping',
            name='subscription',
            field=models.IntegerField(db_column='Subscription', default=None),
        ),
    ]
