# Generated by Django 5.1.5 on 2025-02-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0010_remove_ytmmapping_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytmmapping',
            name='mapping_name',
            field=models.TextField(blank=True, db_column='Mapping Name', null=True),
        ),
        migrations.AlterField(
            model_name='ytmmapping',
            name='mapping_subscription',
            field=models.TextField(blank=True, db_column='Mapping Subscription', null=True),
        ),
        migrations.AlterField(
            model_name='ytmmapping',
            name='subscription',
            field=models.TextField(db_column='Subscription', default=None),
        ),
    ]
