# Generated by Django 5.1.5 on 2025-02-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0013_delete_ytmmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='YtmMapping',
            fields=[
                ('isin', models.TextField(db_column='ISIN', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name', default=None)),
                ('subscription', models.TextField(db_column='Subscription', default=None)),
                ('mapping_isin', models.TextField(blank=True, db_column='Mapping ISIN', null=True)),
                ('mapping_name', models.TextField(blank=True, db_column='Mapping Name', null=True)),
                ('mapping_subscription', models.TextField(blank=True, db_column='Mapping Subscription', null=True)),
                ('hard_coding', models.FloatField(blank=True, db_column='Hard Coding', null=True)),
                ('repo_rate', models.FloatField(blank=True, db_column='Repo Rate', null=True)),
            ],
            options={
                'db_table': 'YtmMapping',
            },
        ),
    ]
