# Generated by Django 5.1.5 on 2025-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0014_ytmmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytmmapping',
            name='instrument_type',
            field=models.TextField(blank=True, db_column='Instrument Type', null=True),
        ),
    ]
