# Generated by Django 5.1.5 on 2025-02-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0016_alter_currencyfactormultiplier_currency_exchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyFactorMultiplier',
        ),
    ]
