# Generated by Django 5.1.5 on 2025-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0018_currencyfactormultiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='brothers',
            name='ticker',
            field=models.TextField(blank=True, db_column='Ticker', null=True),
        ),
    ]
