# Generated by Django 5.1.5 on 2025-02-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0020_alter_brothers_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExposureManual',
            fields=[
                ('isin', models.TextField(db_column='ISIN', primary_key=True, serialize=False)),
                ('ticker', models.TextField(db_column='Ticker')),
                ('currency', models.TextField(db_column='Currency')),
                ('value', models.IntegerField(db_column='Value')),
                ('hedged', models.FloatField(db_column='Hedged')),
            ],
            options={
                'db_table': 'CurrencyExposureManual',
            },
        ),
    ]
