# Generated by Django 5.1.5 on 2025-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0021_currencyexposuremanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexposuremanual',
            name='hedged',
            field=models.TextField(db_column='Hedged'),
        ),
        migrations.AlterField(
            model_name='currencyexposuremanual',
            name='value',
            field=models.FloatField(db_column='Value'),
        ),
    ]
