# Generated by Django 5.1.5 on 2025-02-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0024_delete_currencyexposuremanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExposureManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.TextField(db_column='ISIN')),
                ('ticker', models.TextField(blank=True, db_column='Ticker', null=True)),
                ('currency', models.TextField(db_column='Currency')),
                ('weight', models.FloatField(blank=True, db_column='Weight', null=True)),
                ('hedged', models.TextField(blank=True, db_column='Hedged', null=True)),
            ],
            options={
                'db_table': 'CurrencyExposureManual',
                'unique_together': {('isin', 'currency')},
            },
        ),
    ]
