# Generated by Django 5.1.5 on 2025-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstrumentsApp', '0025_currencyexposuremanual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytmmapping',
            name='repo_rate',
            field=models.TextField(blank=True, db_column='Repo Rate', null=True),
        ),
    ]
