load_strategy_info:
      package_path: C:\AFMachineLearning\Libraries\MarketMonitor\user_strategy\gov
      module_name: botMM
      class_name: botMM


market_monitor:

  instruments:
    - isin: IT0005645509
      description: BOT 14 AP 26 A
      maturity: 2026-04-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005650574
      description: BOT 14 MG 26 A
      maturity: 2026-05-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005680639
      description: BOT 29 MG 26 S
      maturity: 2026-05-29
      reference_ester: null
      multiplier: 10000

    - isin: IT0005655037
      description: BOT 12 GN 26 A
      maturity: 2026-06-12
      reference_ester: null
      multiplier: 10000

    - isin: IT0005660029
      description: BOT 14 LG 26 A
      maturity: 2026-07-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005692485
      description: BOT 31 LG 26 S
      maturity: 2026-07-31
      reference_ester: null
      multiplier: 10000

    - isin: IT0005666851
      description: BOT 14 AG 26 A
      maturity: 2026-08-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005669269
      description: BOT 14 ST 26 A
      maturity: 2026-09-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005674335
      description: BOT 14 OT 26 A
      maturity: 2026-10-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005678492
      description: BOT 13 NV 26 A
      maturity: 2026-11-13
      reference_ester: null
      multiplier: 10000

    - isin: IT0005684888
      description: BOT 14 DC 26 A
      maturity: 2026-12-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005689887
      description: BOT 14 GE 27 A
      maturity: 2027-01-14
      reference_ester: null
      multiplier: 10000

    - isin: IT0005695256
      description: BOT 12 FB 27 A
      maturity: 2027-02-12
      reference_ester: null
      multiplier: 10000

    - isin: IT0005699340
      description: BOT 12 MZ 27 A
      maturity: 2027-03-12
      reference_ester: null
      multiplier: 10000

  rabbit_data_export:
    activate: true      # Impostare true (e redis activate: false) per usare RabbitMQ
    rabbit_params:
      rabbit_host: 'rabbitmq.af.tst'
      rabbit_port: 5672
      rabbit_user: 'mqclient'
      rabbit_password: 'Mqclient-00'
      rabbit_vhost: 'TestCredEQEtf'
      channel_rabbit: trades_rabbit_gov



  trade_manager:
    show_my_trades: True
    time_zero_lag: [5, 10, 30]
    trade_folder: C:\AFMachineLearning\Libraries\MarketMonitor\user_strategy\gov

  tasks:
    update_HF:
      activate: true
      frequency: 0.3
    update_LF:
      activate: true
      frequency: 5
    trade:
      activate: true
      synchronous: true
      frequency: 1

bloomberg_data_distributor:
  activate: true
  interval: 1


kafka_data_distributor:
  activate: true
  kafka_params:
    bootstrap_servers: "aftstserver51.af.pre:9092,aftstserver52.af.pre:9092,aftstserver53.af.pre:9092"
    schema_registry_url: "http://aftstserver51.af.pre:8081"
    start_mode: "latest"  # oppure "earliest"


trade_distributor:
  activate: false
#  path: C:\AFMachineLearning\Libraries\MarketMonitor\etc\marketrades.db
  path: "C:\\Users\\gbs09316\\Documents\\marketTradeFolder\\markettrades.db"

redis_data_distributor:
  activate: true       # Impostare false se si usa rabbit_data_distributor
  redis_params:
    redis_host: 'localhost'
    redis_port: 6379
    redis_db: 0

logging:
  log_level: DEBUG
  log_level_console: WARNING
  log_name: botMM.log
