load_strategy_info:
      package_path: C:\AFMachineLearning\Libraries\MarketMonitor\user_strategy\credit
      module_name: CreditTradeAnalysis
      class_name: CreditTradeAnalysis

timescale_connection:
  host: timescaledb.af.pro
  database: aidb
  port: 5432
  user: aivwr
  password: 63903918ce20c5d534c3eb551202d4ea


market_monitor:

  instruments_list_path: V:\Credit\MarketMonitorDashboards\instruments.xlsx
  api_config_path: C:\AFMachineLearning\Libraries\MarketMonitor\etc\config\bshdata_config.yaml

  book_filter_params:
    tau_seconds: 600
    max_multiplier: 3

  trade_manager:
    time_zero_lags: [10, 20, 30, 40]

  tasks:
    update_HF:
      activate: true
      frequency: 2
    update_LF:
      activate: true
      frequency: 60
    trade:
      activate: true
      synchronous: true
      frequency: 1
    dynamic_params:
      activate: false
      dynamic_config_path: "configFolder/dynamicEquityQuoting.yaml"
      frequency: 1

  rabbit_data_export:
    activate: true      # Impostare true (e redis activate: false) per usare RabbitMQ
    channel: trades_rabbit_credit
    rabbit_params_export:
      rabbit_host: 'rabbitmq.af.tst'
      rabbit_port: 5672
      rabbit_user: 'mqclient'
      rabbit_password: 'Mqclient-00'
      rabbit_vhost: TestCredEQEtf

  redis_data_export:
    activate: true
    channel: trades_redis_credit
    redis_export_params:
      host: localhost
      port: 6379

bloomberg_data_distributor:
  activate: false

kafka_data_distributor:
  activate: true
  kafka_params:
    bootstrap_servers: "aftstserver51.af.pre:9092,aftstserver52.af.pre:9092"#,aftstserver53.af.tst:9092"
    schema_registry_url: "http://aftstserver51.af.pre:8081"
    start_mode: "latest"  # oppure "earliest"

trade_distributor:
  activate: false
  path: "C:\\Program Files\\Banca Sella Holding\\Market Trades Viewer DB\\markettrades.db"

redis_data_distributor:
  activate: false
  redis_params:
    redis_host: 'localhost'
    redis_port: 6379
    redis_db: 0

logging:
  log_level: INFO
  log_level_console: WARNING
  log_name: CreditLiveAnalysis.log


