strategy_name: EtfFiPriceEngine

load_strategy_info:
      package_path: C:\AFMachineLearning\Libraries\MarketMonitor\user_strategy\credit
      module_name: CreditPriceEngine
      class_name: CreditPriceEngine

market_monitor:

  #strategy_name: MarketMonitorDummy

  number_of_days: 12
  price_snipping_time_string: "17:15:00"  # Ricorda di mettere l'ora come stringa in YAML


####pricing params###########################

  pricing:
    driver:
      forecast_aggregation: ewma_outlier
      trimmed_mean:
        perc_outlier: 0.3
      ewma_outlier:
        halflife: 4
        outlier_std: 3

    cluster:
      forecast_aggregation: ewma_outlier
      trimmed_mean:
        perc_outlier: 0.3
      ewma_outlier:
        halflife: 4
        outlier_std: 3

    nav:
      forecast_aggregation: ewma_outlier
      trimmed_mean:
        perc_outlier: 0.3
      ewma_outlier:
        halflife: 2
        outlier_std: 3

    brother:
      forecast_aggregation: ewma_outlier
      trimmed_mean:
        perc_outlier: 0.3
      ewma_outlier:
        halflife: 5
        outlier_std: 3

  tasks:
    update_HF:
      activate: true
      frequency: 1
    update_LF:
      activate: false
      frequency: 60
    data_storing:
      activate: false
      frequency: 300
    trade:
      activate: false
      synchronous: false
      frequency: 1

  sql_db_fi_file: 'C:\AFMachineLearning\Projects\Trading\FxdIncomeEtfAnalysis\FxdIncomeEtfDB.db'


bloomberg_data_distributor:
  activate: true
#    max_var_threshold: 0.05 #max_perc_ret

  bloomberg_params:
    options:
      interval: 0


#gui:
#  Excel:
#      gui_type: ThreadGUIExcel
#      new_instance: false
#      heartbeat:
#        heartbeat_name: "HeartBeatDuma"
#        heartbeat_interval: 20
#        heartbeat_margin: 20
#        # macro_name_heartbeat: "sendPublishingSignal"
#        macro_name_heartbeat: "sendHeartbeat"
#        macro_name_stop: "sendOffSignal"
#      visible: true
#      add_book: false
#      thread_queue_size: 5
#      path: "V:\\ETF\\Risk Management\\Price_Engine_SuperLight.xlsm"



logging:
  log_level: DEBUG
  log_level_console: WARNING
  log_name: CreditPriceEngine.log

oracle_connection:
  environment: PROD
  user: AF_QUANTLIB
  tns_name: ORABOH
  password: b18289f251b94f0e1a819df7c7a0fb2e9fabf457ba67b5bbf584478db8c8c17e
  schema: AF_DATAMART_DBA

timescale_connection:
  host: timescaledb.af.pro
  database: aidb
  port: 5432
  user: aivwr
  password: 63903918ce20c5d534c3eb551202d4ea

 # connection to ts test db
#timescale_connection:
#  host: aftstserveria11.af.tst
#  database: aidb_test
#  port: 5433
#  user: aivwr
#  password: Aivwr-00
